### PR TITLE
Variable selection njmim

### PR DESCRIPTION
**Pull request by egillax**
Added variable selection using normalized join mutual information maximization (NJMIM) and tests.

### CODE REVIEW

**Comment by egillax** [comment]
@AniekMarkus @rossdwilliams 

Could either of you review this so I can merge?

**Comment by AniekMarkus** [comment]
Do we not want the method added as part of VariableSelection.R instead of as algorithm, so that it can be used with any other PLP model via modelSettings (like for e.g. StepwiseSelection)? Or is there a reason why you chose to do it differently?

**Comment by egillax** [comment]
>Do we not want the method added as part of VariableSelection.R instead of as algorithm, so that it can be used with any other PLP model via modelSettings (like for e.g. StepwiseSelection)? Or is there a reason why you chose to do it differently?

I implemented this as a `featureEngineering` method, which can be used with any model in PLP. If I recall correctly our reason for not adding `StepWiseSelection` as a `featureEngineering` method but instead a model was because it returns a model so we could save refitting the model on the selected features by adding it as a model. That's not the case for this method. IMO it's more modular and slightly simpler to have this as a `featureEngineering` method.

**Comment by AniekMarkus** [comment]
> > Do we not want the method added as part of VariableSelection.R instead of as algorithm, so that it can be used with any other PLP model via modelSettings (like for e.g. StepwiseSelection)? Or is there a reason why you chose to do it differently?
> 
> I implemented this as a `featureEngineering` method, which can be used with any model in PLP. If I recall correctly our reason for not adding `StepWiseSelection` as a `featureEngineering` method but instead a model was because it returns a model so we could save refitting the model on the selected features by adding it as a model. That's not the case for this method. IMO it's more modular and slightly simpler to have this as a `featureEngineering` method.

I thought we agreed to implement the various methods in a similar way, and therefore chose the current approach in VariableSelection.R as this is generic to all methods. This way it is easy to apply the different FI selection methods for PLP users. For example, `UnivariateSelection` is also implemented this way (not as `featureEngineering` method) even though it does not lead to a final model. If you believe we should not do this, but have it as `featureEngineering` method instead I'm open for that, but then we should be consistent (and transparent about this design choice).

**Pull request merged**
